### ISSUE TITLE
Web framework choice

### ISSUE THREAD

**Issue by JohnScience** [Calgary-Rust/calgary-rust.github.io#1]
I don't suggest you implementing a web server from scratch unless you are really interested exactly in learning how to do it and not creating a fully functional web server for the website.

As far as I know, **Actix** and **Rocket** are the _most performant_ web frameworks currently available.
https://www.techempower.com/benchmarks/#section=data-r18&hw=ph&test=query

**Actix:**
- Official website: https://actix.rs/
- Crates.io: https://crates.io/crates/actix-web

**Rocket:**
- Official website: https://rocket.rs
- Crates.io: https://crates.io/crates/rocket

Here is a Reddit thread where you can read what people say about these frameworks:
https://www.reddit.com/r/rust/comments/ai6xra/actixweb_vs_rocket/

It seems like the most of Rusticeans prefer **Actix** and I would go for this option.

**Comment by dorfsmay** [comment]
Is this issue's goal to document Rust web framework?

Is it necessary to do so at a local (meetup) level?

Note there are a few "areweXXXyet" dot org sites trying to capture existing efforts from the Rust community in a particular domain. I'd rather add links to those pages on the Calgary-Rust page rather than trying to re-create them.

For web framework, there is:
https://www.arewewebyet.org

**Comment by dorfsmay** [comment]
> It seems like the most of Rusticeans prefer Actix and I would go for this option.

Be careful, a few opinions on a single reddit post is far from representing the community at large.

Some people are wary of these two particular framework. The caveat with Rocket is that it needs [nightly](https://doc.rust-lang.org/1.2.0/book/nightly-rust.html). The caveat with Actix is that it uses a lot of [unsafe blocks](https://doc.rust-lang.org/book/ch19-01-unsafe-rust.html), some people argue more than necessary.

**Comment by dorfsmay** [comment]
I added a paragraph about the areweyet sites on the resource page: 3e52b7d25c18d6709675c6f6db867163013d4f17

Did this answer your questions? Should we close this issue?

**Comment by JohnScience** [comment]
Yes, you can close this issue.
